= Quarto Assignment di Linguaggi e Compilatori

link:QuartoAssignment.pdf[Traccia]

Lo scopo dell'assignment è stato quello di realizzare il passo di *LoopFusion*. +

== Algoritmo

L'algoritmo del passo è suddiviso in due fasi:

=== Controllo sulla possibilità di fusione di due loop

L'esito risulta positivo se vengono soddisfatte le seguenti condizioni: +

- i due loop sono adiacenti
- i due loop ierano lo stesso numero di volte
- i due loop sono control flow equivalenti
- i due loop non contengono dipendenze negative

link:MyLoopFusion.cpp#L5-L64[Funzioni per il controllo]

=== Fusione dei due loop

I due loop vengono fusi in un unico loop.

link:MyLoopFusion.cpp#L66-L123[Fusione]

== link:CMakeLists.txt[]

Inserimento del file sorgente link:MyLoopFusion.cpp[] nel CMake.

== link:PassRegistry.def[]

Aggiunta del passo nel pass manager nella sezione relativa alle funzioni:

[,c++]
----
FUNCTION_PASS("my-loop-fusion", MyLoopFusionPass())
----

== link:PassBuilder.cpp[]

Include dell'header file nel pass manager:

[,c++]
----
#include "llvm/Transforms/Utils/MyLoopFusion.h"
----

== Esecuzione del codice

Una volta inseriti i file nella propria cartella di lavoro, eseguire i seguenti comandi per l'ottimizzazione: +

[,bash]
----
cd build
make opt && make install
cd ..
cd test
clang -O0 -emit-llvm -S -c -Xclang -disable-O0-optnone <fileSorgente>.c -o <fileDaOttimizzare>.ll
opt -p mem2reg <fileDaOttimizzare>.ll -o <fileIntermedio>.bc
llvm-dis <fileIntermedio>.bc -o <fileIntermedio>.ll
opt -p my-loop-fusion <fileIntermedio>.ll -o <fileOttimizzato>.bc
llvm-dis <fileOttimizzato>.bc -o <fileOttimizzato>.ll
----

== Visualizzazione dei Control Flow Graph
----
opt -p dot-cfg <file>.ll
dot -Tpng .<nome_funzione>.dot -o <nome_funzione>.png
----