= Primo Assignment di Linguaggi e Compilatori

link:PrimoAssignment.pdf[Traccia]

== link:LocalOpts.h[]

Header file relativo al passo local-opts.

== link:LocalOpts.cpp[]

File sorgente relativo al passo local-opts. +

Di seguito sono riportati i tre passi LLVM per la realizzazione delle relative ottimizzazioni locali.

=== Algebraic Identity

```
x + 0 = 0 + x ⇒ x
x * 1 = 1 * x ⇒ x
```

==== Funzioni coinvolte

link:LocalOpts.cpp#L24[addBy0]

[source,c++]
----
bool addBy0(BasicBlock::iterator Iter) 
----

Verifica che l'istruzione sia un'addizione e che uno degli operandi sia una costante, più precisamente che sia uno 0, dopodichè sostituisce le references all'addizione con l'operando stesso.

link:LocalOpts.cpp#L105[mulBy1]

[source,c++]
----
bool mulBy1(BinaryOperator *binIter, Value *Other)
----

Verifica che l'istruzione di moltiplicazione abbia una costante tra gli operandi, più precisamente che sia un 1, dopodichè sostituisce le references alla moltiplicazione con l'operando stesso.

=== Strength Reduction

```
15 * x = x * 15 ⇒ (x << 4) - x
y = x / 8 ⇒ y = x >> 3
```

==== Funzioni coinvolte

link:LocalOpts.cpp#L62[mulByPowOf2]

[source,c++]
----
bool mulByPowOf2 (BinaryOperator *binIter, ConstantInt *ci, Value *Other) 
----

Dopo aver controllato che l'istruzione sia una moltiplicazione e che uno degli operandi sia, allo stesso tempo, una costante ed una potenza di due, crea un'istruzione di shift a sinistra. Quest'ultima avrà come operandi il registro presente nella moltiplicazione ed il logaritmo in base due della costante. Dopodichè vengono aggiornate le references alla moltiplicazione con lo shift.

link:LocalOpts.cpp#L72[mulToShift]

[source,c++]
----
bool mulToShift (BinaryOperator *binIter, ConstantInt *ci, Value *Other)
----

Ha la stessa funzionalità di mulByPowOf2 ma lavora con costanti che non siano potenze di due. Crea due istruzioni: uno shift a sinistra e, un'addizione o una sottrazione. Questa decisione dipende dalla differenza tra il valore contenuto nel registro ed il valore del logaritmo in base due più vicino alla costante. Le references alla moltiplicazione vengono passate all'ultima istruzione creata.

link:LocalOpts.cpp#L139[divByPowOf2]

[source,c++]
----
bool divByPowOf2 (BinaryOperator *binIter, ConstantInt *ci, Value *Other)
----

Meccanismo identico a mulByPowOf2 ma applicato alla divisione unsigned. In questo caso l'istruzione creata è uno shift a destra.

link:LocalOpts.cpp#L149[divBy1]

[source,c++]
----
bool divBy1(BinaryOperator *binIter, Value *Other)
----

Come mulBy1, ma per la divisione unsigned.

link:LocalOpts.cpp#L156[zeroDiv]

[source,c++]
----
bool zeroDiv(BinaryOperator *binIter, ConstantInt *ci)
----

In caso di divisione unsigned che abbia 0 come numeratore sostituisce le sue references con la costante 0.

link:LocalOpts.cpp#L112[mulOptimization]

[source,c++]
----
bool mulOptimization(BasicBlock::iterator Iter)
----

link:LocalOpts.cpp#L164[divOptimization]

[source,c++]
----
bool divOptimization (BasicBlock::iterator Iter)
----

Raggruppano un insieme di controlli effettuati sulle istruzioni ed i loro operandi per snellire il codice relativo alle varie casistiche.

=== Multi-Instruction Optimization

```
a = b + 1, c = a - 1, c = b
```

==== Funzioni coinvolte

link:LocalOpts.cpp#L195[multiInstructionOptimization]

[source,c++]
----
bool multiInstructionOptimization(BasicBlock::iterator Iter, BasicBlock &B)
----

Nel caso in cui ci sia un'istruzione che svolge un'operazione e, successivamente, un'istruzione che svolge il calcolo inverso, la funzione modifica le references alla seconda sostituendole con l'operando della prima operazione. Questo permette di rimuovere istruzioni non necessarie.  

== link:CMakeLists.txt[]

Inserimento del file sorgente link:LocalOpts.cpp[] nel CMake.

== link:PassRegistry.def[]

Aggiunta del passo nel pass manager nella sezione relativa ai moduli:

[,c++]
----
MODULE_PASS("local-opts", LocalOpts())
----

== link:PassBuilder.cpp[]

Include dell'header file nel pass manager:

[,c++]
----
#include "llvm/Transforms/Utils/LocalOpts.h"
----

== Esecuzione del codice

Una volta inseriti i file nella propria cartella di lavoro, eseguire i seguenti comandi per l'ottimizzazione: +

[,bash]
----
cd build
make opt && make install
cd ..
cd test
opt -p local-opts <fileDaOttimizzare>.ll -o <fileOttimizzato>.bc
llvm-dis <fileOttimizzato>.bc -o <fileOttimizzato>.ll
----
